### ISSUE TITLE
Mail-Template nutzt falsche Konfig für Webserverprotokol

### ISSUE THREAD

**Issue by fabiante** [nerdakademie/stupa-wahltool#17]
Das URL-Protokoll wird nicht korekt genutzt.

Aus contestantHelper.js:
![image](https://cloud.githubusercontent.com/assets/7669818/23173887/f071ba98-f85a-11e6-9e3b-2990c65502e4.png)

Aus der Konfiguration:
![image](https://cloud.githubusercontent.com/assets/7669818/23173893/f5a9bfe2-f85a-11e6-83f4-1086757ece7e.png)

**Comment by mwohlert** [comment]
Hi.
Danke für deinen Issue :)

Habe ich bereits mit 3c1e189 gefixt

**Comment by mwohlert** [comment]
Wenn dir weitere Fehler auffallen, dann immer gerne n Issue. PR merge ich auch aber vorerst dann nur auf den development branch
