### ISSUE TITLE
Maximale Zeichenlänge für Beschreibungstext?

### ISSUE THREAD

**Issue by vo55** [nerdakademie/stupa-wahltool#19]
Damit der nicht aus dem Kärtchen rausläuft.

**Comment by mwohlert** [comment]
Schlecht zu übprüfen, da eine neue Zeile auch nur ein Zeichen ist.
Kann damit nicht garantiert werden. Hab erstmal overflow scroll gemacht.

Wenn du eine bessere Lösung weißt immer her damit.
Habe max 1500 Zeichen mit 8515aeb eingeführt

**Comment by vo55** [comment]
Gibt es keine Möglichkleit newlines zu erkennen und das dann als z.B. 50 Zeichen zu zählen?

**Comment by mwohlert** [comment]
Die festgeschriebene Height ist nicht schön wörkt aber erstmal
