### ISSUE TITLE
Ich möchte nicht teilnehmen

### ISSUE THREAD

**Issue by vo55** [nerdakademie/stupa-wahltool#22]
Nutzer sollen die Möglichkeit bekommen, sich von der Wahl ausschließen zu können, damit sie nicht aufgestellt werden können.

**Comment by mwohlert** [comment]
Ich schlage 2 Stufen vor:
Die aktuelle Aufstellung löschen
und
Das Aufstellen für diesen Studenten ganz unterbinden

**Comment by philipbarwi** [comment]
+1

**Comment by mwohlert** [comment]
Die grundsätzliche Frage ist:
Legen wir dafür eine extra Seite an auf der man eine der beiden Möglichkeiten auswählen kann, oder sollen dann zwei Links in der Email mitgesandt werden?

**Comment by vo55** [comment]
Würde einfach zwei Links mitschicken
"Aufstellung verwerfen" "Ich möchte generell nicht aufgestellt werden"

Irgendwie so.

**Comment by malteschluenz** [comment]
Ich bin für die 2 Links. Unter der Vorraussetzung, dass man sich nur 1 mal aufstellen kann, wäre der mit der ewigen Deaktivierung m.E. sogar unnötig, da solange man nicht reagiert kann man auch nicht nochmal eingetragen werden...

**Comment by mwohlert** [comment]
Backend ready a031894

**Comment by mwohlert** [comment]
Funktion gestestet
