### ISSUE TITLE
Stimmenvergabe für die Wahl selbst

### ISSUE THREAD

**Issue by FiniH** [nerdakademie/stupa-wahltool#23]
Die Frage kam auf, ob man, wenn man sich nicht entscheiden kann, statt 4 nur 3 Stimmen abgeben kann.
Ist ja sicherlich möglich, daher schonmal der Hinweis. :)

**Comment by mwohlert** [comment]
Wenn das so erlaubt ist wäre das sicherlich möglich.
Aber ich hätte gerne eine offizielle Bestätigung vom Stupa 
@maxSchumann

**Comment by maxSchumann** [comment]
Klar, man muss natürlich keine vier Stimmen abgeben.
Und an jede Person kann man nur eine Stimme vergeben

**Comment by mwohlert** [comment]
Alles klar.
Dann wird das so bei der Implementierung der Abstimmungsfunktion berüchsichtigt
