### ISSUE TITLE
Mailversand

### ISSUE THREAD

**Issue by mwohlert** [nerdakademie/stupa-wahltool#8]
Mailversand mit NodeMailer und Email Templates einrichten

**Comment by malteschluenz** [comment]
Also theoretisch sollte die Klasse Mailer mit den Funktionen ´jetzt funktionieren... Ich werde die Methoden gleich noch mal kommentieren

**Comment by mwohlert** [comment]
Funktioniert nun korrekt. Danke für die vorarbeit

**Comment by mwohlert** [comment]
Pooled Mailing implementieren

**Comment by mwohlert** [comment]
Funktioniert super
